services:
  - type: web
    name: swiftstay-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    plan: free
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: swiftstaynigeria-postgress-project
          property: connectionString
      - key: PAYSTACK_SECRET
        value: sk_test_xxxxx
      - key: FLUTTERWAVE_SECRET
        value: FLWSECK-xxxxx
      - key: AI_PROVIDER
        value: openai
      - key: AI_API_KEY
        value: replace_with_your_key
      - key: AI_API_BASE
        value: ""
      - key: AI_MODEL
        value: gpt-4o-mini
      - key: NODE_ENV
        value: development

databases:
  - name: swiftstaynigeria-postgress-project
    databaseName: swiftstaynigeria_postgress_project
    user: swiftstaynigeria_postgress_project_user

DATABASE_URL=postgresql://<user>:<password>@<host>:5432/<dbname>
